services:
  ghost:
    image: ghost:6-alpine
    container_name: anotes
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - mariadb
    environment:
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: zenusr
      database__connection__password: strongPass!2024
      database__connection__database: anotes
      url: http://localhost:2368
      # NODE_ENV=production
    volumes:
      - content:/var/lib/ghost/content

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongPass!2024
      MYSQL_DATABASE: anotes
      MYSQL_USER: zenusr
      MYSQL_PASSWORD: strongPass!2024
    volumes:
      - db:/var/lib/mysql

volumes:
  content:
  db:
