services:
  ghost:
    image: ghost:6-alpine
    container_name: anotes
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - mariadb
    env_file:
      - ./env/anotes.env
    environment:
      url: http://localhost:2368
      # NODE_ENV=development
    volumes:
      - ./content:/var/lib/ghost/content

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    expose:
      - 3306:3306
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - ./db:/var/lib/mysql

volumes:
  content:
  db:
